baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "post/"
      weight: 2
    - name: About
      url: "about/"
      weight: 3
    - name: Categories
      url: "categories/"
      weight: 4
    - name: Tags
      url: "tags/"
      weight: 5


params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Lukasz Rabalski](https://www.linkedin.com/in/%C5%82ukasz-r%C4%85balski-2892b8102) 2017 -- {Year}"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
